include: 'https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml'

stages:
- build

flatpak:
  extends: .flatpak
  image: registry.gitlab.gnome.org/gnome/gnome-runtime-images/gnome:master
  stage: build
  variables:
    MANIFEST_PATH: "demo/io.gnome.Aperture.Demo.json"
    RUNTIME_REPO: "https://flathub.org/repo/flathub.flatpakrepo"
    FLATPAK_MODULE: "libaperture"
    MESON_ARGS: ""
    APP_ID: "io.gnome.Aperture.Demo"
    BUNDLE: "aperture-demo.flatpak"

