include: 'https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml'

stages:
- build
- publish

flatpak:
  extends: .flatpak
  image: registry.gitlab.gnome.org/gnome/gnome-runtime-images/gnome:master
  stage: build
  variables:
    MANIFEST_PATH: "demo/io.gnome.Aperture.Demo.json"
    RUNTIME_REPO: "https://flathub.org/repo/flathub.flatpakrepo"
    FLATPAK_MODULE: "libaperture"
    MESON_ARGS: ""
    APP_ID: "io.gnome.Aperture.Demo"
    BUNDLE: "aperture-demo.flatpak"

fedora:
  image: registry.gitlab.gnome.org/gnome/gtk/fedora-docs:v19
  stage: build
  script:
    - meson --buildtype=release _build
    - ninja -C _build aperture-doc
    - mv _build/doc/html/ _reference/
  artifacts:
    paths:
    - _reference

pages:
  stage: publish
  dependencies:
  - fedora
  script:
  - mv _reference public
  artifacts:
    paths:
    - public
  only:
  - master

